export const USER_ACTIVE = "USER_ACTIVE";
export const USER_ACTIVE_LOADING = "USER_ACTIVE_LOADING";

export const GET_TENANTS = "GET_TENANTS";
export const GET_TENANTS_LOADING = "GET_TENANTS_LOADING";

export const TENANTS_DETAIL = "TENANTS_DETAIL";
export const TENANTS_DETAIL_LOADING = "TENANTS_DETAIL_LOADING";

export const FLAGGED_TENANTS_LIST = "FLAGGED_TENANTS_LIST"


// contractors
export const GET_CONTRACTORS = "GET_CONTRACTORS";
export const GET_CONTRACTORS_LOADING = " GET_CONTRACTORS_LOADING";
export const CONTRACTORS_DETAIL = "CONTRACTORS_DETAIL";
export const CONTRACTORS_DETAIL_LOADING = "CONTRACTORS_DETAIL_LOADING";


// projects
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_LOADING = " GET_PROJECTS_LOADING";

export const PROJECT_DETAIL = "PROJECT_DETAIL";
export const PROJECT_DETAIL_LOADING = "PROJECT_DETAIL_LOADING";


// schedule
export const FILTER_SCHEDULE = "FILTER_SCHEDULE";
export const FILTER_SCHEDULE_LOADING = " FILTER_SCHEDULE_LOADING";

export const SINGLE_SCHEDULE = 'SINGLE_SCHEDULE';
export const SINGLE_SCHEDULE_LOADING = " SINGLE_SCHEDULE_LOADING";

export const GET_TASK = 'GET_TASK';
export const GET_TASK_LOADING = " GET_TASK_LOADING";


// support_team
export const GET_SUPPORT = "GET_SUPPORT";
export const GET_SUPPORT_LOADING = "GET_SUPPORT_LOADING";

export const SUPPORT_DETAIL = "SUPPORT_DETAIL";
export const SUPPORT_DETAIL_LOADING = "SUPPORT_DETAIL_LOADING";

// get profile data 
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";

// assign conctortra data type 
export const GET_ASSIGN_CONTRACTORS = "GET_ASSIGN_CONTRACTORS";
export const DELETE_ASSIGN_CONTRACTORS = "DELETE_ASSIGN_CONTRACTORS";
export const RESET_ASSIGN_CONTRACTORS = "RESET_ASSIGN_CONTRACTORS";

// assign conctortra data type 
export const GET_ASSIGN_TENANTS = "GET_ASSIGN_TENANTS";
export const DELETE_ASSIGN_TENANTS = "DELETE_ASSIGN_TENANTS";
export const RESET_ASSIGN_TENANTS = "RESET_ASSIGN_TENANTS";


// get incidents 
export const GET_INCIDENTS = "GET_INCIDENTS";
export const GET_INCIDENTS_LOADING = "GET_INCIDENTS_LOADING";
export const INCIDENTS_DETAILS = 'INCIDENTS_DETAILS';
export const INCIDENTS_DETAILS_LOADING = 'INCIDENTS_DETAILS_LOADING'


// Expenses 
export const GET_EXPENSES_LOADING = 'GET_EXPENSES_LOADING'
export const GET_EXPENSES = 'GET_EXPENSES'
export const EXPENSES_DETAILS_LOADING = 'EXPENSES_DETAILS_LOADING';
export const EXPENSES_DETAILS = 'EXPENSES_DETAILS';

// Project Request 
export const GET_PPROJECT_REQUEST_LOADING = 'GET_PPROJECT_REQUEST_LOADING'
export const GET_PPROJECT_REQUEST = 'GET_PPROJECT_REQUEST'

// GET_MANAGER_LIST Request 
export const GET_MANAGER_LIST_LOADING = 'GET_MANAGER_LIST_LOADING'
export const GET_MANAGER_LIST = 'GET_MANAGER_LIST'

// GET_TENANTS_PROJECT_REQUEST Request 
export const GET_TENANTS_PROJECT_REQUEST_LOADING = 'GET_TENANTS_PROJECT_REQUEST_LOADING'
export const GET_TENANTS_PROJECT_REQUEST = 'GET_TENANTS_PROJECT_REQUEST'
export const GET_TENANTS_PROJECT_REQUEST_DETAILS_LOADING = 'GET_TENANTS_PROJECT_REQUEST_DETAILS_LOADING';
export const GET_TENANTS_PROJECT_REQUEST_DETAILS = 'GET_TENANTS_PROJECT_REQUEST_DETAILS';

// GET_TENANTS_MESSAGE type 
export const GET_TENANTS_MESSAGE_LOADING = 'GET_TENANTS_MESSAGE_LOADING'
export const GET_TENANTS_MESSAGE = 'GET_TENANTS_MESSAGE'
export const GET_TENANTS_MESSAGE_DETAILS_LOADING = 'GET_TENANTS_MESSAGE_DETAILS_LOADING';
export const GET_TENANTS_MESSAGE_DETAILS = 'GET_TENANTS_MESSAGE_DETAILS';

// GET_TENANTS_MESSAGE type 
export const GET_ADMIN_MESSAGE_LOADING = 'GET_ADMIN_MESSAGE_LOADING'
export const GET_ADMIN_MESSAGE = 'GET_ADMIN_MESSAGE'


// emergency_contacts Types 

export const GET_EMERGENCY_CONTACTS_LOADING = 'GET_EMERGENCY_CONTACTS_LOADING'
export const GET_EMERGENCY_CONTACTS = 'GET_EMERGENCY_CONTACTS'
export const GET_EMERGENCY_CONTACTS_DETAILS_LOADING = 'GET_EMERGENCY_CONTACTS_DETAILS_LOADING';
export const GET_EMERGENCY_CONTACTS_DETAILS = 'GET_EMERGENCY_CONTACTS_DETAILS';

// emergency_contacts Types 

// secure_notes Types 

export const GET_SECURE_NOTES_LOADING = 'GET_SECURE_NOTES_LOADING'
export const GET_SECURE_NOTES = 'GET_SECURE_NOTES'
export const GET_SECURE_NOTES_DETAILS_LOADING = 'GET_SECURE_NOTES_DETAILS_LOADING';
export const GET_SECURE_NOTES_DETAILS = 'GET_SECURE_NOTES_DETAILS';

// secure_notes Types

//stripe account types
export const CHECK_STRIPE_USER = 'CHECK_STRIPE_USER';
export const CHECK_STRIPE_USER_LOADING = 'CHECK_STRIPE_USERCHECK_STRIPE_USER_LOADING';
export const CREATE_ONE_TIME_PAYMENT = "CREATE_ONE_TIME_PAYMENT"
export const CREATE_ONE_TIME_PAYMENT_LOADING = "CREATE_ONE_TIME_PAYMENT_LOADING"
export const CREATE_CONNECT_ACCOUNT_STRIPE = "CREATE_CONNECT_ACCOUNT_STRIPE"
export const CREATE_CONNECT_ACCOUNT_STRIPE_LOADING = "CREATE_CONNECT_ACCOUNT_STRIPE_LOADING"

// get all transactions
export const GET_ALL_TRANSACTION = 'GET_ALL_TRANSACTION';
export const GET_ALL_TRANSACTION_LOANING = 'GET_ALL_TRANSACTION_LOANING'

// get all current payment transaction
export const GET_CURRENT_TRANSACTION = 'GET_CURRENT_TRANSACTION';
export const GET_CURRENT_TRANSACTION_LOANING = 'GET_CURRENT_TRANSACTION_LOANING'

